#:schema https://github.com/SchemaStore/schemastore/raw/0890a3e1872731b569e66903f32abe669a970b8a/src/schemas/json/air-verse-air.json
[build]
pre_cmd = [
    "tailwindcss -m -i ./frontend/input.css -o ./assets/tailwind.css",
    "templ generate --notify-proxy",
]
cmd = "go build -o ./tmp/main ."
exclude_dir = ["assets", "tmp", "testdata", "node_modules", "migrations"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go", "sql\\/.*\\.go", "tailwind.css"]
include_ext = ["go", "sql", "templ", "css"]
