/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: proto/messages.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class AnalyseVideoMessage extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        upload_id?: number;
        video_id?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("upload_id" in data && data.upload_id != undefined) {
                this.upload_id = data.upload_id;
            }
            if ("video_id" in data && data.video_id != undefined) {
                this.video_id = data.video_id;
            }
        }
    }
    get upload_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set upload_id(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get video_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set video_id(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        upload_id?: number;
        video_id?: number;
    }): AnalyseVideoMessage {
        const message = new AnalyseVideoMessage({});
        if (data.upload_id != null) {
            message.upload_id = data.upload_id;
        }
        if (data.video_id != null) {
            message.video_id = data.video_id;
        }
        return message;
    }
    toObject() {
        const data: {
            upload_id?: number;
            video_id?: number;
        } = {};
        if (this.upload_id != null) {
            data.upload_id = this.upload_id;
        }
        if (this.video_id != null) {
            data.video_id = this.video_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.upload_id != 0)
            writer.writeInt64(1, this.upload_id);
        if (this.video_id != 0)
            writer.writeInt64(2, this.video_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AnalyseVideoMessage {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AnalyseVideoMessage();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.upload_id = reader.readInt64();
                    break;
                case 2:
                    message.video_id = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): AnalyseVideoMessage {
        return AnalyseVideoMessage.deserialize(bytes);
    }
}
